"""
Django settings for lumenore_apps project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.lumenore_apps.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.lumenore_apps.com/en/4.2/ref/settings/
"""

from pathlib import Path
from .constants import Constants
import os
constant = Constants()

financeApp = constant.get_conn_info('financeApp')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.lumenore_apps.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "pkttgz6y#n+v@rv8xpzph9k!a)z#o+kf3aczy$lqsm+f@kcf@-"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# LOGIN_URL = 'login'

ALLOWED_HOSTS = ['.lumenore.com', "*"]

CSRF_TRUSTED_ORIGINS = ['https://*.lumenore.com',]
CORS_ALLOWED_ORIGINS = ('https://*.lumenore.com',"http://localhost:8080","http://localhost:3000")
CORS_ORIGIN_WHITELIST = ("http://localhost:3000",)

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # "taskmanager.apps.TaskmanagerConfig",
    # "livesync",

    'finance.apps.FinanceConfig',
    'rest_framework',
]

SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 1800



REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'TEST_REQUEST_RENDERER_CLASSES': [
        'rest_framework.renderers.MultiPartRenderer',
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.TemplateHTMLRenderer'
    ],
    'TEST_REQUEST_DEFAULT_FORMAT': 'json'
}

LOGGING_CONFIG = None

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "lumenore_apps.middleware.middleware",
]

MIDDLEWARE_CLASSES = ("livesync.core.middleware.DjangoLiveSyncMSiddleware",)

ROOT_URLCONF = "lumenore_apps.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "taskmanager/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "lumenore_apps.wsgi.application"


# Database
# https://docs.lumenore_apps.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3"
    },
    "financeApp":{
        "ENGINE": financeApp.get("driver"),
        "NAME": financeApp.get("database"),
        "USER": financeApp.get("user"),
        "HOST": financeApp.get("host"),
        "PORT": financeApp.get("port"),
        "PASSWORD": financeApp.get("password")

    }
}


# Password validation
# https://docs.lumenore_apps.com/en/4.2/ref/settings/#auth-password-validators

# AUTH_USER_MODEL = "taskmanager.TmUser"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.lumenore_apps.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.lumenore_apps.com/en/4.2/howto/static-files/

STATIC_URL = 'apps/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "apps/static/")
]

STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = 'apps/media/'

# Default primary key field type
# https://docs.lumenore_apps.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
