# Generated by Django 4.2.7 on 2023-11-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_alter_tmtask_tm_source_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmtaskinfo',
            name='created_on',
            field=models.DateTimeField(default='YYYY-MM-DD HH:mm:ss.SSSSSS', editable=False),
        ),
    ]
