# Generated by Django 4.2.7 on 2023-11-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_alter_ticket_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
